name: Update Wiki with Comments

on:
  push:
    branches:
      - main  # یا هر شاخه دیگری که می‌خواهید این Action روی آن اجرا شود

jobs:
  update_wiki:
    runs-on: ubuntu-latest  # یا هر سیستم عاملی که برای پروژه شما مناسب است

    steps:
      # مرحله اول: چک کردن مخزن
      - name: Check out repository
        uses: actions/checkout@v2

      # مرحله دوم: استخراج کامنت‌ها از فایل‌های سورس کد
      - name: Extract comments from source code
        run: |
          # استخراج کامنت‌ها از تمام فایل‌های کد (در اینجا فقط فایل‌های Rust)
          grep -r "//" ./src > comments.md

      # مرحله سوم: به‌روزرسانی Wiki
      - name: Update Wiki
        uses: devops-infra/action-push-to-wiki@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # توکن دسترسی به GitHub
          wiki_repo: samantrader/rustdesk/wiki"  # جایگزین با اطلاعات مخزن Wiki شما
          file_path: "comments.md"  # فایل Markdown که کامنت‌ها در آن ذخیره شده‌اند
